AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Read Only Policy

Parameters:
  Environment:
    Type: String
    Default: ent-it-staging
  ProjectName:
    Type: String
    Default: safe-iac-demo
  RegionControl:
    Type: String
    Default: us-east-1

Resources:
  S3ReadOnlyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${ProjectName}-${Environment}-s3-readonly"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: ListBucket
            Effect: Allow
            Action: s3:ListBucket
            Resource: arn:aws:s3:::iac-s3-demo-bucket
          - Sid: ObjectAccess
            Effect: Allow
            Action: s3:GetObject
            Resource: arn:aws:s3:::iac-s3-demo-bucket/*

Outputs:
  PolicyArn:
    Value: !Ref S3ReadOnlyPolicy
    Export:
      Name: !Sub "${ProjectName}-${Environment}-S3ReadOnlyPolicyArn"
