AWSTemplateFormatVersion: "2010-09-09"

Resources:
  DeveloperRole:
    Type: AWS::IAM:Role
    Properties:
      RoleName: developer-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action: sts:AssumeRole
