AWSTemplateFormatVersion: "2010-09-09"
Description: Developer Role

Parameters:
  Environment:
    Type: String
    Default: ent-it-staging
  ProjectName:
    Type: String
    Default: safe-iac-demo
  RegionControl:
    Type: String
    Default: us-east-1

Resources:
  DeveloperRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: developer-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action: sts:AssumeRole
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: AWSService
          Value: iam
        - Key: RegionControl
          Value: !Ref RegionControl

      ManagedPolicyArns:
        - !ImportValue S3ReadOnlyPolicyArn
