AWSTemplateFormatVersion: "2010-09-09"
Description: S3 bucket + Lambda

Parameters:
  Environment:
    Type: String
    Description: "Target environment"
  ProjectName:
    Type: String
  RegionControl:
    Type: String

Resources:
  AppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: iac-s3-demo-bucket
      Tags:
        - Key: AWSService
          Value: s3

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: lambda-execution-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Tags:
        - Key: AWSService
          Value: iam

      Policies:
        - PolicyName: lambda-logs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource: "*"

  AppLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: test-lambda-function
      Runtime: python3.9
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          def handler(event, context):
              return "Hello from Lambda"
      Tags:
        - Key: AWSService
          Value: lambda
