name: Deploy Identity

# Trigger workflow on push to main or manual trigger
on:
  push:
    branches:
      - main
    paths:
      - "identity/**"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        required: true
        default: "dev"

jobs:
  deploy-identity:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configure AWS credentials from GitHub secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy S3 ReadOnly Policy stack
        run: |
          aws cloudformation deploy \
            --template-file identity/policies/s3-readonly.yaml \
            --stack-name safe-s3-readonly-policy \
            --capabilities CAPABILITY_NAMED_IAM \
            --tags Environment=ent-it-staging ProjectName=safe-iac-demo RegionControl=us-east-1 AWSService=cloudformation

      - name: Deploy IAM roles stack
        run: |
          aws cloudformation deploy \
            --template-file identity/roles/developer-role.yaml \
            --stack-name safe-developer-role \
            --capabilities CAPABILITY_NAMED_IAM \
            --tags Environment=ent-it-staging ProjectName=safe-iac-demo RegionControl=us-east-1 AWSService=cloudformation
